---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: sample-api-service-pod
spec:
  containers:
    - name: sample-api-service
      image: nicc777/sample-api-service:v2
      ports:
        - name: service-port
          containerPort: 8080
          hostPort: 8280
      livenessProbe:
        httpGet:
          path: /liveness
          port: service-port
        failureThreshold: 1
        periodSeconds: 10
      startupProbe:
        httpGet:
          path: /readiness
          port: service-port
        failureThreshold: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /readiness
          port: service-port
        initialDelaySeconds: 5
        periodSeconds: 5
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"
