apiVersion: apps/v1 
kind: Deployment
metadata:
  name: sample-api-deployment-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
      - image: nicc777/sample-api-service:v2
        name: sample-api
        ports:
        - containerPort: 8080
          name: sample-api-port
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.5"
          requests:
            memory: "128Mi"
