---
apiVersion: v1
kind: Service
metadata:
  name: sample-api-lb-service
spec:
  selector:
    app: sample-api
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
